# Generated by Django 4.1 on 2022-09-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(blank=True, max_length=50)),
                (
                    "primary_role",
                    models.CharField(
                        choices=[
                            ("Full-Stack Engineer", "full-stack-engineer"),
                            ("Frontend Engineer", "frontend-engineer"),
                            ("Backend Engineer", "backend-engineer"),
                            ("DevOps Engineer", "devops-engineer"),
                            ("Mobile Developer", "mobile-developer"),
                            ("Data Engineer", "data-engineer"),
                            ("Data Scientist", "data-scientist"),
                        ],
                        default="full-stack-engineer",
                        max_length=50,
                    ),
                ),
                ("experience", models.CharField(blank=True, max_length=1024)),
                ("skills", models.TextField(blank=True, max_length=1024, null=True)),
                ("education", models.CharField(blank=True, max_length=500)),
                ("bio", models.TextField(blank=True, max_length=200, null=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("mobile", models.CharField(max_length=15, unique=True)),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=10, null=True)),
                ("country", models.CharField(max_length=100)),
                ("website", models.URLField(blank=True, max_length=1000)),
                ("linkedln", models.URLField(blank=True, max_length=1000)),
                ("github", models.URLField(blank=True, max_length=1000)),
                (
                    "resume",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/resume/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="applied",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
